name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  lint_format:
    name: Lint & Format on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 linter
        run: flake8 app/

      - name: Check code formatting with Black
        run: black --check app/

  notify:
    name: Notify on CI Result
    if: always()
    needs: lint_format
    uses: ./.github/workflows/reusable-notify.yml
    with:
      status: ${{ needs.lint_format.result }}
      message: "CI Lint & Format completed on all OS targets with status: ${{ needs.lint_format.result }}"
